# Generated by Django 5.0.6 on 2024-06-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersessioninfo',
            old_name='evice_token',
            new_name='device_token',
        ),
        migrations.AddField(
            model_name='usersessioninfo',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='token_blacklist.outstandingtoken'),
        ),
    ]
